### PR TITLE
Add tools: v2rayA, Passwall, Leaf

### PR DESCRIPTION
**Pull request by yuhan6665**

### CODE REVIEW

**Comment by ghost** [comment]
Should Passwall be here?

**Comment by yuhan6665** [comment]
Why not, it is a UI tool that contains v2ray binary

**Comment by nicholascw** [comment]
- v2rayA is already in.
- Leaf looks good enough to me.
- The Passwall one I didn't get it, there's no license included and the link it's pointing to has no well-documented tutorial or user instructions.

**Comment by nicholascw** [comment]
Closed due to the conflict with the v2rayA item already in. You may open a separated new PR for Leaf. As for Passwall, it seems it doesn't fit in the lists' various criteria.

**Pull request closed without merging**
