### PR TITLE
Improve documentation and document mptcp for v5 config format

### PR DESCRIPTION
**Pull request by arinc9**
Hello. This patch series improves the documentation of v2ray-core and documents Multipath TCP for the v5 configuration format.

### CODE REVIEW

**Comment by arinc9** [comment]
I've pushed a small change to address a typo on one of the patch subjects.

**Comment by xiaokangwang** [comment]
Thanks... There are quite a lot of edits, it will take longer to review some of them like lower casing all the links...

**Comment by arinc9** [comment]
No worries! Let me know if you have any comments regarding the changes.

**Review by xiaokangwang — APPROVED** [review]
I believe this pull request is ready to be merged. I have verify that lower-case hashtag is the correct format. Thanks for your contribution!

**Pull request merged**
