### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by zhvb**

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
Apparently that are not typos.

**Comment by zhvb** [comment]
> Apparently that are not typos.

well i tested not working with single \
double \\ works

**Comment by database64128** [comment]
> double \ works

I think that's how JSON escapes charaters like `\`, not how regular expressions work.

**Comment by zhvb** [comment]
> > double \ works
> 
> I think that's how JSON escapes charaters like `\`, not how regular expressions work.

agreed

**Comment by zhvb** [comment]
well anyway 
this pull been closed
im going delete my fork

**Pull request closed without merging**
