### PR TITLE
add: trojan complete

### PR DESCRIPTION
**Pull request by mkmark**
motivated by https://github.com/v2fly/v2ray-core/pull/3084
if considered appropriate, other protocols shall follow suit

### CODE REVIEW

**Comment by xiaokangwang** [comment]
@AkinoKaede would you mind have a look if the updated document would be appropriate when it comes to understood by power users?

**Comment by AkinoKaede** [comment]
> @AkinoKaede would you mind have a look if the updated document would be appropriate when it comes to understood by power users?

It may be a little difficult to understood, it would be better if a sample configuration could be added.

**Comment by mkmark** [comment]
done

**Review by AkinoKaede — APPROVED** [review]

**Comment by xiaokangwang** [comment]
I think this pull request is ready to be merged! Thanks for your contribution!

**Pull request merged**
