### PR TITLE
Use relative links

### PR DESCRIPTION
**Pull request by kidonng**

### CODE REVIEW

**Comment by rikkihamano** [comment]
`.md` would not be avaliable after being generated into a static site.
e.g.
image

**Comment by rikkihamano** [comment]
`../../` can be replaced with `/`

**Comment by kidonng** [comment]
> `.md` would not be avaliable after being generated into a static site.

VuePress will convert it into real links.

> `../../` can be replaced with `/`

Use relative links makes it work in both editors (like VSCode) and website.

**Comment by kidonng** [comment]
I found some other links to fix, it could be put into this PR together🤦‍♂️ Never mind, I will just open a new one

**Pull request merged**
