### PR TITLE
Update start.md - 建议使用         "domainStrategy": "AsIs" （默认值）对小白用户更加友好

### PR DESCRIPTION
**Pull request by huangsen365**
建议使用         "domainStrategy": "AsIs" （默认值）对小白用户更加友好

### CODE REVIEW

**Comment by database64128** [comment]
Newbies are not the documentation's target audience.

**Comment by kslr** [comment]
But "IPOnDemand" is rarely use 🧐

**Comment by database64128** [comment]
> But "IPOnDemand" is rarely use monocle_face

For me, I use `IPOnDemand` intensively 😁.

**Comment by huangsen365** [comment]
Never mind, we found a better example from https://github.com/XTLS/Xray-examples/tree/main/VMess-TCP

**Pull request closed without merging**
