### PR TITLE
Update tools.md

### PR DESCRIPTION
**Pull request by ghost**
Add https://github.com/2dust/v2rayNG

### CODE REVIEW

**Comment by AkinoKaede** [comment]
It is not based on V2Ray now.

**Comment by ghost** [comment]
But the author did say so in README.md, is anything wrong ?
image

**Comment by AkinoKaede** [comment]
> But the author did say so in README.md, is anything wrong ? image

Yes, the description is wrong.

**Comment by ghost** [comment]
OK, I see. Thank you for your comment

**Pull request closed without merging**
